NDefines.NGraphics.COMMANDGROUP_PRESET_COLORS_HSV = {
    -- 0.0/360.0, 0.81, 0.6,
    -- 30.0/360.0, 0.8, 0.5,
    -- 56.0/360.0, 1, 0.8,
    -- 110.0/360.0, 0.80, 0.3,
    -- 110.0/360.0, 0.80, 0.5,
    -- 210.0/360.0, 0.80, 0.5,		
    -- 297.0/360.0, 0.66, 0.5,
    -- 297.0/360.0, 0.81, 0.6,
    -- 0.0/360.0, 0.00, 1.00,
    -- 0.0, 0.00, 1.00

    0.0/360.0, 0.81, 0.4,
    30.0/360.0, 0.8, 0.3,
    56.0/360.0, 1, 0.5,
    110.0/360.0, 0.80, 0.2,
    110.0/360.0, 0.80, 0.4,
    210.0/360.0, 0.80, 0.4,
    297.0/360.0, 0.66, 0.3,
    297.0/360.0, 0.81, 0.4,
    0.0/360.0, 0.00, 1.00,
    0.0, 0.00, 1.00
}

-- borders
NDefines.NGraphics.GRADIENT_BORDERS_FIELD_COUNTRY_REFRESH = 30
NDefines.NGraphics.GRADIENT_BORDERS_CAMERA_DISTANCE_OVERRIDE_STATE = 1.0
NDefines.NGraphics.GRADIENT_BORDERS_CAMERA_DISTANCE_OVERRIDE_SUPPLY_AREA = 0.0
NDefines.NGraphics.GRADIENT_BORDERS_CAMERA_DISTANCE_OVERRIDE_STRATEGIC_REGIONS = 1.0
NDefines.NGraphics.GRADIENT_BORDERS_CAMERA_DISTANCE_OVERRIDE_RESISTANCE = 0.0
NDefines.NGraphics.GRADIENT_BORDERS_CAMERA_DISTANCE_OVERRIDE_FACTIONS = 0.0
NDefines.NGraphics.GRADIENT_BORDERS_THICKNESS_STATE = 45.0
NDefines.NGraphics.GRADIENT_BORDERS_THICKNESS_SUPPLY_AREA_B = 15.0
NDefines.NGraphics.GRADIENT_BORDERS_THICKNESS_STRATEGIC_REGIONS = 50.0

NDefines.NGraphics.GRADIENT_BORDERS_OUTLINE_CUTOFF_COUNTRY = 1.0
NDefines.NGraphics.GRADIENT_BORDERS_OUTLINE_CUTOFF_STATE = 0.98
NDefines.NGraphics.GRADIENT_BORDERS_OUTLINE_CUTOFF_SUPPLY_AREA = 0.995
NDefines.NGraphics.GRADIENT_BORDERS_OUTLINE_CUTOFF_STRATEGIC_REGIONS = 0.973
NDefines.NGraphics.GRADIENT_BORDERS_OUTLINE_CUTOFF_RESISTANCE = 1.0
NDefines.NGraphics.GRADIENT_BORDERS_OUTLINE_CUTOFF_FACTIONS = 1.0

NDefines.NGraphics.BORDER_COLOR_SELECTION_STATE_R = 1.0
NDefines.NGraphics.BORDER_COLOR_SELECTION_STATE_G = 0.62
NDefines.NGraphics.BORDER_COLOR_SELECTION_STATE_B = 0.33
NDefines.NGraphics.BORDER_COLOR_SELECTION_STATE_A = 1.5
NDefines.NGraphics.BORDER_COLOR_SELECTION_PROVINCE_R = 1.0
NDefines.NGraphics.BORDER_COLOR_SELECTION_PROVINCE_G = 0.32
NDefines.NGraphics.BORDER_COLOR_SELECTION_PROVINCE_B = 0.15
NDefines.NGraphics.BORDER_COLOR_SELECTION_PROVINCE_A = 1.5
NDefines.NGraphics.BORDER_COLOR_SELECTION_SUPPLY_AREA_R = 1.0
NDefines.NGraphics.BORDER_COLOR_SELECTION_SUPPLY_AREA_G = 0.62
NDefines.NGraphics.BORDER_COLOR_SELECTION_SUPPLY_AREA_B = 0.33
NDefines.NGraphics.BORDER_COLOR_SELECTION_SUPPLY_AREA_A = 1.5

NDefines.NGraphics.BORDER_WIDTH = 1.2
NDefines.NGraphics.STATE_BORDER_FADE_NEAR = 500
NDefines.NGraphics.STATE_BORDER_FADE_FAR = 505


-- -- AIR
NDefines.NAirGfx.MAX_MISSILE_BOMBING_SCENARIOS = 1
NDefines.NAirGfx.MAX_BOMBING_SCENARIOS = 1
NDefines.NAirGfx.MAX_PATROL_SCENARIOS = 1
NDefines.NAirGfx.MAX_DOGFIGHTS_SCENARIOS = 1
NDefines.NAirGfx.MAX_TRANSPORT_SCENARIOS = 1
NDefines.NAirGfx.MAX_SCOUT_SCENARIOS = 1
NDefines.NAirGfx.AIRPLANES_ANIMATION_GLOBAL_SPEED_PER_GAMESPEED = {0.3, 0.3, 0.3, 0.3, 0.3, 0.3}
NDefines.NAirGfx.AIRPLANES_SMOOTH_INTERPOLATION_MOVE = 0.02
NDefines.NAirGfx.AIRPLANES_SMOOTH_INTERPOLATION_TURN = 0.02
-- MAP
NDefines.NMapMode.RADAR_ROTATION_SPEED = 0.025
NDefines.NMapMode.AIR_RANGE_INDICATOR_ROTATION_SPEED = 0.0000
NDefines.NMapIcons.DEFAULT_PRIORITY_NAVAL_BASE = 10
NDefines.NGraphics.MAX_TRAIN_WAGON_COUNT = 1
NDefines.NGraphics.DRAW_FOW_CUTOFF = 0 -- ?
NDefines.NGraphics.DRAW_FOW_FADE_LENGTH = 0 -- ?
NDefines.NGraphics.DRAW_SHADOWS_FADE_LENGTH = 0
NDefines.NGraphics.TREE_FADE_NEAR = 150.0
NDefines.NGraphics.CITY_SPRAWL_SHRINK_DISTANCE = 200
NDefines.NGraphics.TREE_FADE_FAR = 250.0
NDefines.NGraphics.BLOOM_WIDTH = 0
NDefines.NGraphics.BLOOM_SCALE = 0
NDefines.NGraphics.BRIGHT_THRESHOLD = 0

NDefines.NGraphics.EMISSIVE_BLOOM_STRENGTH = 0
NDefines.NFrontend.CAMERA_MAX_HEIGHT = 3500 --3000.0
NDefines.NFrontend.CAMERA_MIN_HEIGHT = 40 --50.0

-- -- new
NDefines.NGraphics.CAPITAL_ICON_CUTOFF = 500
NDefines.NGraphics.NAVALBASE_ICON_DISTANCE_CUTOFF = 500
NDefines.NGraphics.AIRBASE_ICON_DISTANCE_CUTOFF = 500
NDefines.NGraphics.RADAR_ICON_DISTANCE_CUTOFF = 300
NDefines.NGraphics.WEATHER_DISTANCE_CUTOFF = 600
NDefines.NGraphics.WEATHER_DISTANCE_FADE_LENGTH = 100
NDefines.NGraphics.SHIPS_DISTANCE_CUTOFF = 80
NDefines.NGraphics.MAP_BUILDINGS_SHRINK_DISTANCE = 70

NDefines.NGraphics.TOOLTIP_DELAYED_DELAY = 0.01
NDefines.NGraphics.TOOLTIP_SHOW_DELAY = 0.01
NDefines.NGraphics.TOOLTIP_HIDE_DELAY = 0.01

NDefines.NGraphics.FRIEND_COLOR  = {1.0, 1.0, 1.0}
NDefines.NGraphics.NEUTRAL_COLOR = {0.8, 0.8, 0.8}
NDefines.NGraphics.BLOOM_SCALE = 0.0